# Config.yaml
name: "Glyphrz-server"
port: 8888
logAddress: "./log/"

mysql:
  name: "root"
  host: "127.0.0.1"
  port: 3306
  password: "Hou812712~"
  dbName: "Glyphrz"

redis:
  host: "127.0.0.1"
  port: 6379

jwt:
  key: "7zNo45ObYUzb4qQ662ib8ohCLnXXwUVL"